# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Install NBGV tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv

- script: nbgv cloud
  displayName: Set Version

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: pack
    packagesToPack: ./ClrMD.Extensions/ClrMD.Extensions.csproj"
    packDirectory: $(Build.ArtifactStagingDirectory)\Packages
    configuration: $(BuildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    artifactName: Packages
    publishLocation: Container
